CREATE VIEW CustomerDetails
AS

SELECT C.CUSTOMER_ID, 
	   C.CUSTOMER_NAME, 
	   C.CUSTOMER_EMAIL, 
	   CONCAT(A.ADDRESSLINE1, ', ', 
			  A.ADDRESSLINE2,', ', 
			  A.CITY,', ', 
			  A.COUNTRY,'-', 
			  A.ZIP) AS ADDRESS ,
	   C.CUSTOMER_PHONE
FROM CUSTOMER AS C
	JOIN ADDRESSES AS A
		ON C.CUSTOMER_ADDRESS = A.ADDRESS_ID


SELECT * FROM CustomerDetails;