USE WholesaleInventory;
GO

CREATE VIEW DuesByCustomers 
AS
	WITH CustomerDue ( CUSTOMER_ID, DUE)
	   AS
	   (
			SELECT CUSTOMER_ID, SUM(AMOUNT_DUE) AS DUE
			FROM ORDERS 
			WHERE SALE_OR_PURCHASE = 1 AND AMOUNT_DUE != 0 
			GROUP BY CUSTOMER_ID
		)
		
	SELECT C.CUSTOMER_NAME, 
		   CONCAT(A.ADDRESSLINE1,
				  A.ADDRESSLINE2,
				  A.CITY,
				  A.ZIP,
				  A.COUNTRY) AS ADDRESS, 
			D.DUE  
	FROM CustomerDue AS D 
	  JOIN CUSTOMER AS C 
	    ON D.CUSTOMER_ID = C.CUSTOMER_ID 
	  JOIN ADDRESSES AS A 
	    ON A.ADDRESS_ID = C.CUSTOMER_ADDRESS;

GO

SELECT * FROM DuesByCustomers;
